# Generated by Django 5.0.2 on 2024-02-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Agent', 'Agent'), ('Company', 'Company')], default='client', max_length=20),
        ),
    ]
