# Generated by Django 5.0.2 on 2024-02-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_approved_customuser_registration_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_type',
        ),
    ]
