# Generated by Django 5.0.2 on 2024-02-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_hotellisting_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotellisting',
            name='images',
        ),
        migrations.AddField(
            model_name='hotellisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='house_list'),
        ),
    ]
