# Generated by Django 5.0.2 on 2024-02-21 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_hotellisting_images_hotellisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellisting',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotellisting',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='house_list'),
        ),
    ]
