# Generated by Django 5.0.2 on 2024-02-21 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_hotellisting_user_alter_hotellisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellisting',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
