# Generated by Django 5.0.2 on 2024-02-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_hotellisting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotellisting',
            name='user',
        ),
        migrations.AlterField(
            model_name='hotellisting',
            name='image',
            field=models.ImageField(blank=True, default='house_list', null=True, upload_to='house_list'),
        ),
    ]
