# Generated by Django 5.0.2 on 2024-02-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_hotellisting_user_alter_hotellisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellisting',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='house_list'),
        ),
    ]
